// <auto-generated />
namespace LambAndLentil.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PluralClassesID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PluralClassesID));
        
        string IMigrationMetadata.Id
        {
            get { return "201707131720118_PluralClassesID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
