// <auto-generated />
namespace LambAndLentil.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tryAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201706211724059_tryAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
